### ISSUE TITLE
Invalid API Key when touch LoginWithAmazon

### ISSUE THREAD

**Issue by nickwhsu** [evil0327/Alexa-On-Android#1]
你好, 我試過你prebuilt 的AlexaDemo.apk , 非常好用, 感謝你的分享
我將你的code 重新build 過後, 並 touch LoginWithAmazeon 的button 會出現以下的error :
請問是需要重新申請一組自己的 api_key 嗎? 謝謝! 

05-23 05:01:31.964 26044-26044/alexademo.ellison.test.alexademo W/com.amazon.identity.auth.device.appid.APIKeyDecoder: Failed to decode: Decoding failed: certificate fingerprint can't be verified! pkg=alexademo.ellison.test.alexademo
    Unable to decode APIKey for pkg=alexademo.ellison.test.alexademo
05-23 05:01:31.964 26044-26044/alexademo.ellison.test.alexademo D/AndroidRuntime: Shutting down VM
05-23 05:01:31.965 26044-26044/alexademo.ellison.test.alexademo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: alexademo.ellison.test.alexademo, PID: 26044
    java.lang.IllegalArgumentException: Invalid API Key
        at com.amazon.identity.auth.device.authorization.InternalAuthManager.<init>(InternalAuthManager.java:58)
        at com.amazon.identity.auth.device.authorization.InternalAuthManager.getInstance(InternalAuthManager.java:47)
        at com.amazon.identity.auth.device.api.authorization.AuthorizationManager.authorize(AuthorizationManager.java:191)
        at alexademo.ellison.test.alexademo.util.LoginManager.doLogin(LoginManager.java:120)
        at alexademo.ellison.test.alexademo.MainActivity$1.onClick(MainActivity.java:76)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by evil0327** [comment]
你好，感謝花時間試玩這個專案。我用自己帳號登入是沒問題的，看來是因為api key跟帳號有綁定關係，所以你應該是要自己申請一個api key，可以參考這篇教學 https://blog.csdn.net/qq_27061049/article/details/80167376 
申請後api key放在assets/api_key.txt，另外string.xml裡面的product_id也要換成你申請的Product ID，有問題的話歡迎再討論喔

**Comment by nickwhsu** [comment]
ok~謝謝!我試著改看看!
